# Generated by Django 2.1.1 on 2018-10-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attended', models.DateField(verbose_name='date')),
                ('inout', models.BooleanField(verbose_name='input')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(help_text='Course id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='Course name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_crn', models.CharField(help_text='section crn', max_length=5, primary_key=True, serialize=False)),
                ('lecture_day', models.DateTimeField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.CharField(help_text='student number', max_length=9, primary_key=True, serialize=False)),
                ('student_name', models.CharField(help_text='student name', max_length=50)),
                ('student_surname', models.CharField(help_text='student surname', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Course')),
                ('student_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_no', models.CharField(help_text='teacher id', max_length=9, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(help_text='teacher name', max_length=50)),
                ('teacher_surname', models.CharField(help_text='teacher surname', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Teacher'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_crn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
    ]
