# Generated by Django 2.1.1 on 2018-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20181130_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='studentPhotos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_day',
            field=models.CharField(choices=[('MON.', 'Monday'), ('TUES.', 'Tuesday'), ('WED.', 'Wednesday'), ('THU.', 'Thursday'), ('FRI.', 'Friday')], max_length=10),
        ),
    ]
