# Generated by Django 2.1.1 on 2018-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181205_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='classphoto',
            name='document2',
            field=models.ImageField(blank=True, upload_to='classPhoto/'),
        ),
    ]
