# Generated by Django 2.1.1 on 2018-12-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_classphoto_document2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classphoto',
            name='document2',
        ),
    ]
